VERILOG_SOURCES = $(PWD)/../hdl/PWM.v\
				  $(PWD)/../hdl/down_clocking_odd.v\
				  $(PWD)/../hdl/down_clocking_even.v\
				  $(PWD)/../hdl/minus_one.v
TOPLEVEL=PWM
MODULE=test_PWM
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
